//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AreaZeusRechner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5709")]
        public string KostenAreaArea {
            get {
                return ((string)(this["KostenAreaArea"]));
            }
            set {
                this["KostenAreaArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14865")]
        public string KostenAreaZeus {
            get {
                return ((string)(this["KostenAreaZeus"]));
            }
            set {
                this["KostenAreaZeus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public string KostenAreaGenV2 {
            get {
                return ((string)(this["KostenAreaGenV2"]));
            }
            set {
                this["KostenAreaGenV2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2519")]
        public string KostenZeusArea {
            get {
                return ((string)(this["KostenZeusArea"]));
            }
            set {
                this["KostenZeusArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18055")]
        public string KostenZeusZeus {
            get {
                return ((string)(this["KostenZeusZeus"]));
            }
            set {
                this["KostenZeusZeus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public string KostenZeusGenV2 {
            get {
                return ((string)(this["KostenZeusGenV2"]));
            }
            set {
                this["KostenZeusGenV2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2519")]
        public string Kosten80OrbArea {
            get {
                return ((string)(this["Kosten80OrbArea"]));
            }
            set {
                this["Kosten80OrbArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18055")]
        public string Kosten80OrbZeus {
            get {
                return ((string)(this["Kosten80OrbZeus"]));
            }
            set {
                this["Kosten80OrbZeus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public string Kosten80OrbGenV2 {
            get {
                return ((string)(this["Kosten80OrbGenV2"]));
            }
            set {
                this["Kosten80OrbGenV2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9672,48")]
        public string InitialFP {
            get {
                return ((string)(this["InitialFP"]));
            }
            set {
                this["InitialFP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21890,88")]
        public string InitialFe {
            get {
                return ((string)(this["InitialFe"]));
            }
            set {
                this["InitialFe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20028,75")]
        public string InitialSt {
            get {
                return ((string)(this["InitialSt"]));
            }
            set {
                this["InitialSt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5082,00")]
        public string InitialVV {
            get {
                return ((string)(this["InitialVV"]));
            }
            set {
                this["InitialVV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17734,13")]
        public string InitialCh {
            get {
                return ((string)(this["InitialCh"]));
            }
            set {
                this["InitialCh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("630,05")]
        public string InitialEi {
            get {
                return ((string)(this["InitialEi"]));
            }
            set {
                this["InitialEi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("151,90")]
        public string InitialWa {
            get {
                return ((string)(this["InitialWa"]));
            }
            set {
                this["InitialWa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17027,25")]
        public string InitialEn {
            get {
                return ((string)(this["InitialEn"]));
            }
            set {
                this["InitialEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57")]
        public string BgFe {
            get {
                return ((string)(this["BgFe"]));
            }
            set {
                this["BgFe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string BgSt {
            get {
                return ((string)(this["BgSt"]));
            }
            set {
                this["BgSt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11,67")]
        public string BgVV {
            get {
                return ((string)(this["BgVV"]));
            }
            set {
                this["BgVV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49,83")]
        public string BgCh {
            get {
                return ((string)(this["BgCh"]));
            }
            set {
                this["BgCh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string BgEi {
            get {
                return ((string)(this["BgEi"]));
            }
            set {
                this["BgEi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string BgWa {
            get {
                return ((string)(this["BgWa"]));
            }
            set {
                this["BgWa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-41,25")]
        public string BgEn {
            get {
                return ((string)(this["BgEn"]));
            }
            set {
                this["BgEn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public string SimUntil {
            get {
                return ((string)(this["SimUntil"]));
            }
            set {
                this["SimUntil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string ZeusPlanis {
            get {
                return ((string)(this["ZeusPlanis"]));
            }
            set {
                this["ZeusPlanis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-23,33")]
        public string BgForFe {
            get {
                return ((string)(this["BgForFe"]));
            }
            set {
                this["BgForFe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11,67")]
        public string BgForSt {
            get {
                return ((string)(this["BgForSt"]));
            }
            set {
                this["BgForSt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string BgVorVV {
            get {
                return ((string)(this["BgVorVV"]));
            }
            set {
                this["BgVorVV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string BgForCh {
            get {
                return ((string)(this["BgForCh"]));
            }
            set {
                this["BgForCh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string BgForEi {
            get {
                return ((string)(this["BgForEi"]));
            }
            set {
                this["BgForEi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string BgForWa {
            get {
                return ((string)(this["BgForWa"]));
            }
            set {
                this["BgForWa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-11,67")]
        public string BgForEn {
            get {
                return ((string)(this["BgForEn"]));
            }
            set {
                this["BgForEn"] = value;
            }
        }
    }
}
